# Generated by Django 2.2 on 2019-11-08 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='subcategory',
        ),
    ]
