# Generated by Django 2.2 on 2019-11-08 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_remove_shop_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='facilities',
        ),
    ]
