# Generated by Django 2.2 on 2019-11-08 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_remove_shop_facilities'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='shop',
            new_name='shops',
        ),
    ]
