# Generated by Django 2.2 on 2019-11-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20191108_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prod',
            field=models.CharField(db_index=True, default='tractor', max_length=20),
            preserve_default=False,
        ),
    ]
