# Generated by Django 2.2 on 2019-11-08 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_product_prod'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subcat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='service.SubCategory'),
            preserve_default=False,
        ),
    ]
