# Generated by Django 2.2 on 2019-11-08 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_product_subcat'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='shopcat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='service.Shop'),
            preserve_default=False,
        ),
    ]
