# Generated by Django 2.2 on 2019-11-10 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_subcategory_shopcat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='area_p',
        ),
        migrations.RemoveField(
            model_name='product',
            name='time_p',
        ),
    ]
