# Generated by Django 2.2 on 2019-11-10 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_auto_20191110_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='b_price',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
    ]
