# Generated by Django 2.2 on 2019-11-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_product_b_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='user',
        ),
        migrations.AddField(
            model_name='feedback',
            name='name',
            field=models.CharField(default='ayush', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='sub',
            field=models.CharField(default='farmket', max_length=300),
            preserve_default=False,
        ),
    ]
