# Generated by Django 2.2 on 2019-11-11 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_auto_20191110_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
    ]
