# Generated by Django 2.2 on 2019-11-11 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_remove_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='address',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='city',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='nos',
        ),
    ]
