# Generated by Django 2.2 on 2019-12-16 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0016_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
