# Generated by Django 2.2 on 2020-02-01 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200131_0031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
        migrations.AddField(
            model_name='order',
            name='addr',
            field=models.CharField(default='address', max_length=760),
            preserve_default=False,
        ),
    ]
